server:
  port: 8501

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/
  boot:
    admin:
      client:
        url: http://localhost:8508

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    instance:
      hostname: localhost
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spcloud:
  cassandra:
    contact:
      point: localhost
    cluster:
      contact:
        point: 192.168.1.113
    point: 9042
    keyspace:
      name: springcloud

    username: cassandra.
    password: cassandra.